import React from 'react';
import { Cpu, Shield, Music, Code, Gamepad, Mic, Monitor, Zap, Star, Bot, Trophy, Compass, Palette, Camera, Target, Brain, Cog, PenTool, Film, MessageSquare, BookOpen, ChefHat, Layers, Puzzle, Dice1, Sparkles, Lightbulb, Flame, Search, Building, Pencil } from 'lucide-react';

const DEFAULT_EVENTS = [
  // ===== ROBOTICS =====
  { 
    id: 'robo-race', 
    name: 'Robo Race', 
    fee: 100, 
    limit: '1 Member', 
    desc: 'Build and race your robot through challenging tracks.', 
    iconName: 'Bot',
    fullDescription: 'Design a fast, agile robot and race it through an obstacle-filled track! Teams must build autonomous or remote-controlled robots that can navigate turns, ramps, and hurdles. The fastest robot to complete the track wins!',
    rules: [
      '1 Registration is compulsory for all participants or teams before the race',
      '2 Each team can have only one robot in the competition',
      '3 Robots must follow the given size and weight limits set by organizers',
      '4 The robot must be controlled manually or wirelessly (no fully autonomous bots unless allowed)',
      '5 The race will be conducted on a fixed track with obstacles',
      '6 Robots must stay on the track – leaving the track may lead to penalties or disqualification',
      '7 Damaging other robots is strictly prohibited',
      '8 Teams must complete the track within the given time limit',
      '9 Judging is based on speed, control, and successful completion of obstacles',
      '10 Judges’ decision will be final and binding',
      'Robot Specification:',
      '1 The maximum dimension of the robot can be 30 cm x 30 cm x 30 cm (l x b x h)',
      '2 The robot may be wired or wireless',
      '3 AC supply will be provided in the college',
      '4 The length of the wire (for wired bots) should be long enough to cover the whole track and wire should remain slack during the complete run',
      '5 Maximum weight must not exceed 3 kg',
      '6 The machine must be powered electrically only Use of IC engine is not allowed',
      '7 Batteries must be sealed, immobilized electrolyte type (gel cell, lithium, NiCad, or dry cells)',
      '8 The electric voltage anywhere in the machine should not be more than 12 V DC at any point of time'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Pradeep Chaudhary', phone: '8401889146' }, { name: 'Dax Padasala', phone: '' }, { name: 'Hiren Ajakiya', phone: '7863840941' }]
  },
  { 
    id: 'robo-war', 
    name: 'Robo War', 
    fee: 100, 
    limit: '1 Member', 
    desc: 'Build and battle your robots in the ultimate arena.', 
    iconName: 'Shield',
    fullDescription: 'Design, build, and battle your robot in the most thrilling event of PRAXES 2K26! Robots will face off in a specially designed arena. The last robot standing wins!',
    rules: [
      '1 Each team can have a maximum of 4 – 5 members',
      '2 The robot must follow the size and weight limits given by organizers',
      '3 Matches are conducted between two robots in an arena',
      '4 The goal is to immobilize, flip, or push the opponent out of the arena',
      '5 Each match will have a fixed time duration (eg, 3 – 5 minutes)',
      '6 No Dangerous Weapons – Use of explosives, fire, liquids, or harmful weapons is strictly prohibited',
      '7 Intentional damage to the arena or unfair tactics will lead to disqualification',
      '8 Robots must be controlled manually or wirelessly; no external interference allowed',
      '9 Teams must follow all safety instructions during the match',
      '10 Winners are decided based on damage, control, aggression, and strategy, and the judges’ decision is final',
      'Robot Specification:',
      '1 Permissible weight: Maximum 06 kg (excluding off‐bot power equipment eg batteries, adapters etc)',
      '2 Maximum permissible volume Fully unfolded robot must be within the limits of 40 cm X 55 cm (l x b) There is no maximum height for a robot (dictated by the design and weight constraints)',
      '3 Robots can have weapons such as cutters, flippers, saws, lifting devices, spinning hammers etc Use of liquid projectiles, any kind of inflammable liquid, flame‐based weapons, radio jamming devices, high power magnets or electromagnets, are not permitted',
      '4 Use of IC Engines is not allowed',
      '5 We will provide on‐site power points of 230 V AC Participating teams need to bring their own adapters/converters (with a maximum output voltage of 24 V DC) to avail AC supply',
      '6 In case of batteries, maximum allowed voltage is 24 V DC',
      '7 If robot is wired, then maximum 45 m length is permitted'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Pradeep Chaudhary', phone: '8401889146' }, { name: 'Dax Padasala', phone: '' }, { name: 'Hiren Ajakiya', phone: '7863840941' }]
  },
  { 
    id: 'robo-soccer', 
    name: 'Robo Soccer', 
    fee: 100, 
    limit: '1 Member', 
    desc: 'Control your robot to score goals in a thrilling soccer match.', 
    iconName: 'Bot',
    fullDescription: 'Build a robot that can play soccer! Teams compete in a custom arena, controlling their robots to score goals. Strategy, control, and teamwork are key to winning this exciting event.',
    rules: [
      'Robot Specification:',
      '• The robot must fit within a square the box of the following dimensions initially: Height: 30 cm Width: 30cm Length: 30cm',
      '• The total mass of the robot must not exceed 6 kg',
      '• Robots must be manually controlled Wired or wireless remotes can be used',
      '• Teams using wireless robots should use multi - frequency remotes to avoid frequency interference',
      '• Only one member would be allowed to control the bot during the match',
      '• The robot should be electrically powered The power supply must be on - board',
      '• The potential difference between any two points of the robot should not exceed 24V DC',
      '• Change of battery will not be allowed during the match',
      '• In the case of wired bots, the wires should remain slack during the fight',
      '• The wires should remain insulated and all the wires coming out of the machine should be stacked as a single unit',
      '• Parts that could break or damage the ring or opponent',
      '• Use of pneumatics, hydraulics, inflammable liquids, flame weapons, glue, RF jammers, and electromagnetic systems are strictly prohibited',
      '• The robots should not hold or grab the ball while moving Dribbler mechanisms can be used',
      '• The ball can be dribbled and hit from any part of the robot',
      '• Each bot must have a mechanism to hit the ball Hydraulics should not be used for any mechanisms'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Pradeep Chaudhary', phone: '8401889146' }, { name: 'Dax Padasala', phone: '' }, { name: 'Hiren Ajakiya', phone: '7863840941' }]
  },

  // ===== TECHNICAL EVENTS =====
  { 
    id: 'constructo', 
    name: 'Constructo', 
    fee: 70, 
    limit: '1 Member', 
    desc: 'Build creative structures using limited materials.', 
    iconName: 'Building',
    fullDescription: 'Put your engineering and creative skills to the test! Teams will be given limited materials to build structures that are judged on strength, creativity, and aesthetics. A true test of innovation and teamwork.',
    rules: [
      '1 Popsicle sticks',
      '2 Paper',
      '3 Glue ● Dimensions:',
      '• Maximum',
      '1 Length - 12 cm',
      '2 Width - 12 cm',
      '3 Height – 40 cm',
      '• Minimum',
      '1 Length – 10cm',
      '2 Width - 10 cm',
      '3 Height - 30cm The Competition :',
      '1 Reporting of the participating team should be 15 minutes before the start of the event',
      '2 Maximum 3 members in a team will be allowed',
      '3 Teams will be given 2 hours for construction of the tower using the material provided on the day of the event',
      '4 No outside material will be allowed to be used during the time of the event'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Bhumika Prajapati', phone: '' }, { name: 'Nilesh Gelot', phone: '9328509383' }, { name: 'Hardik Chaudhary', phone: '9499775348' }]
  },
  { 
    id: 'constructo-squad', 
    name: 'Constructo(Squad)', 
    fee: 280, 
    limit: '4 Member', 
    desc: 'Build creative structures using limited materials with a squad.', 
    iconName: 'Building',
    fullDescription: 'Put your engineering and creative skills to the test in a team of 4! Teams will be given limited materials to build structures that are judged on strength, creativity, and aesthetics. A true test of innovation and teamwork.',
    rules: [
      '1 Popsicle sticks',
      '2 Paper',
      '3 Glue ● Dimensions:',
      '• Maximum',
      '1 Length - 12 cm',
      '2 Width - 12 cm',
      '3 Height – 40 cm',
      '• Minimum',
      '1 Length – 10cm',
      '2 Width - 10 cm',
      '3 Height - 30cm The Competition :',
      '1 Reporting of the participating team should be 15 minutes before the start of the event',
      '2 Maximum 4 members in a team will be allowed',
      '3 Teams will be given 2 hours for construction of the tower using the material provided on the day of the event',
      '4 No outside material will be allowed to be used during the time of the event'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Bhumika Prajapati', phone: '' }, { name: 'Nilesh Gelot', phone: '9328509383' }, { name: 'Hardik Chaudhary', phone: '9499775348' }]
  },
  { 
    id: 'quiz-o-tech', 
    name: 'Quiz-O-Tech', 
    fee: 100, 
    limit: '4 Member', 
    desc: 'Test your technical knowledge in this exciting quiz.', 
    iconName: 'Brain',
    fullDescription: 'How well do you know technology? From computer science to engineering marvels, this quiz covers it all. Compete in multiple rounds of technical trivia and prove that your team is the smartest in the room!',
    rules: [
      '1 Qualifying Round',
      '• Quiz can be played in 1,2 or 3 person',
      '• Maximum number of member in team is',
      '3',
      '• Phones are not allowed while quiz is going on',
      '• Students who are qualified can go to round',
      '1',
      '• Qualification is based on merit',
      '• If someone is doing cheating then he/she will be disqualified',
      '2 Rules of Round - 1',
      '• A question will be asked to a team and if they are unable to answer, it will be passed to the next team if, the next team are unable to answer then it will be passed to the audience',
      '• Each team would be asked 5 question',
      '• 10 marks for correct answer and 5 negative marks for wrong answer',
      '• If a team cannot answer the question, they can pass the question and then the question would be forwarded to the next team',
      '• Answering time is only 60 seconds',
      '• Team discussion is allowed',
      '3 Rules of Round - 2',
      '• Each team will be asked 5 question one after another',
      '• 10 marks for the correct answer and negative 5 marks for the wrong answer',
      '• Answering time is only 30 seconds',
      '• If a team cannot answer the question, they can move for the next question The question will not be forwarded to the next team'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Dhruvi Patel', phone: '' }, { name: 'Anju Paregi', phone: '' }, { name: 'Talha Manashia', phone: '' }, { name: 'Pratik Prajapati', phone: '' }]
  },
  { 
    id: 'cadventure', 
    name: 'CADventure', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Showcase your CAD design skills.', 
    iconName: 'Cpu',
    fullDescription: 'Put your Computer Aided Design skills to the test! Participants will be given engineering problems and must create accurate 2D/3D models using CAD software. Speed, accuracy, and creativity will be judged.',
    rules: [
      '• Participants may be provided with specific design criteria or constraints they must adhere to when creating their CAD models',
      '• Participants might be required to use a specific CAD software or a set of approved CAD tools for the competition',
      '• There will be rules regarding the format and submission process for CAD files This could include file type, naming conventions, and submission deadlines',
      '• Typically, participants must create original CAD designs and may not plagiarize or use pre - existing designs without permission',
      '• There will be clearly defined reasons for disqualification, such as violating the rules, engaging in unethical behavior, or failing to meet submission deadlines',
      '• The time given for 2d design will be 20 minutes and for 3d drawing time will be 30 minutes',
      '• The one who complete the drawing before the time limit and with proper accuracy then he/she will be winner'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Rahul Chaudhary', phone: '' }]
  },
  { 
    id: 'coding', 
    name: 'Coding', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Solve challenging programming problems under pressure.', 
    iconName: 'Code',
    fullDescription: 'A competitive programming contest where participants solve algorithmic challenges in languages like C, C++, Java, or Python. Test your problem-solving skills and coding speed!',
    rules: [
      '• Only C language Allowed  ( If participate students are more we can allow the other languages) ( Depend on participants Students)',
      '• Statements are different for everyone',
      '• Limited time for writing code',
      '• No internet allowed',
      '• Software : - Dev C++',
      '• Mobile, smart watch and no other electrical devices allowed',
      '• Coordinator decision is the final decision'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Pragat Patel', phone: '9727021685' }, { name: 'Tarni Patel', phone: '' }]
  },
  { 
    id: 'pcb-design', 
    name: 'PCB Master', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Design printed circuit boards like a pro.', 
    iconName: 'Cog',
    fullDescription: 'Demonstrate your PCB design skills! Participants will be given circuit specifications and must design a working PCB layout using design software. Accuracy, efficiency, and component placement will be evaluated.',
    rules: [
      '• Objective',
      '• The competition is based on the analysis of analog circuit components behavior and the input output characteristics of different circuits, like filter, clipping, clamping circuits',
      '• General rules',
      '• The registration fee per individual will be 50 Rs, group of maximum 3 person is allowed',
      '• The components for competition will be provided by event organizer',
      '• The rounds/stages of completion will be from beginner to theoretical and the last round will be practical basis',
      '• The final winner and runner up will be decided by performance and final decision will be decided by the event coordinator',
      '• The winner and runner up will be awarded with certificate and trophy',
      '• Technical specification of event',
      '• First round will be technical inspection type',
      '• Second round will be theoretical analysis type on paper competition, in which various circuit diagrams will be provided for analysis as per specifications',
      '• Third and final round will be based on breadboard based practical circuit analysis',
      '• The evaluation will be based on the timing and efficiency of output/ performance'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Payal Chamachiya', phone: '' }, { name: 'Divyang Patel', phone: '9428450393' }]
  },
  { 
    id: 'electro', 
    name: 'Electro', 
    fee: 30, 
    limit: '1 Member', 
    desc: 'Test your electronics and circuit knowledge.', 
    iconName: 'Zap',
    fullDescription: 'A hands-on electronics challenge! Participants must identify components, build circuits, and troubleshoot electronic systems. Perfect for electronics and electrical engineering enthusiasts.',
    rules: [
      'Robot Specification:',
      '• The robot must fit within a square the box of the following dimensions initially: Height: 30 cm Width: 30cm Length: 30cm',
      '• The total mass of the robot must not exceed 6 kg',
      '• Robots must be manually controlled Wired or wireless remotes can be used',
      '• Teams using wireless robots should use multi - frequency remotes to avoid frequency interference',
      '• Only one member would be allowed to control the bot during the match',
      '• The robot should be electrically powered The power supply must be on - board',
      '• The potential difference between any two points of the robot should not exceed 24V DC',
      '• Change of battery will not be allowed during the match',
      '• In the case of wired bots, the wires should remain slack during the fight',
      '• The wires should remain insulated and all the wires coming out of the machine should be stacked as a single unit',
      '• Parts that could break or damage the ring or opponent',
      '• Use of pneumatics, hydraulics, inflammable liquids, flame weapons, glue, RF jammers, and electromagnetic systems are strictly prohibited',
      '• The robots should not hold or grab the ball while moving Dribbler mechanisms can be used',
      '• The ball can be dribbled and hit from any part of the robot',
      '• Each bot must have a mechanism to hit the ball Hydraulics should not be used for any mechanisms'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: []
  },
  { 
    id: 'poster-presentation', 
    name: 'Poster Presentation', 
    fee: 100, 
    limit: '1 Member', 
    desc: 'Present your technical ideas through creative posters.', 
    iconName: 'PenTool',
    fullDescription: 'Communicate your innovative ideas, research, or projects through a visually appealing poster. Teams will present their work to a panel of judges. Clarity, creativity, and technical depth will be evaluated.',
    rules: [
      '1 Registration is compulsory for all participants',
      '2 Poster must follow the given theme or topic',
      '3 Poster size should be as per guidelines (eg, A1/A2 size)',
      '4 Content must be original and created by participants only',
      '5 Poster should be neat, clear, and well - organized',
      '6 Participants must be present to explain their poster to judges',
      '7 Use of proper headings, diagrams, and visuals is encouraged',
      '8 No offensive or inappropriate content is allowed',
      '9 Judging will be based on creativity, content, and presentation skills',
      '10 Judges’ decision will be final and binding'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Chirag Hadiyal', phone: '7863025984' }, { name: 'Khushi Prajapati', phone: '' }]
  },
  { 
    id: 'exhibition', 
    name: 'Exhibition', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Showcase your innovative projects and prototypes.', 
    iconName: 'Lightbulb',
    fullDescription: 'Bring your projects, prototypes, and innovations to life! The Exhibition gives teams a platform to showcase working models, apps, hardware projects, or any technical creation. The most impressive exhibit wins!',
    rules: [
      '1 All participants must register before the exhibition begins',
      '2 Exhibits should follow the given theme or topic',
      '3 Participants must set up their models/displays on time',
      '4 Each participant or team must be present at their stall during the exhibition',
      '5 Exhibits must be original and prepared by participants only',
      '6 Participants should be ready to explain their exhibit to judges and visitors',
      '7 Use of dangerous materials is not allowed without permission',
      '8 Maintain cleanliness and proper arrangement of the stall area',
      '9 Respect judges, visitors, and other participants',
      '10 No touching or damaging others’ exhibits',
      '11 Follow all instructions given by organizers Judges’ decision will be final'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Utsav Bhalala', phone: '9099020464' }, { name: 'Ankit khumawat', phone: '' }, { name: 'Arpit Chodhary', phone: '' }]
  },
  { 
    id: 'ai-prompt-battle', 
    name: 'AI Prompt Battle', 
    fee: 30, 
    limit: '1 Member', 
    desc: 'Master the art of AI prompting and creative outputs.', 
    iconName: 'Sparkles',
    fullDescription: 'The future is AI! Compete in this unique event where participants craft the best prompts for AI tools to generate creative outputs — images, text, code, or more. The most creative and effective prompt engineer wins!',
    rules: [
      '1 Each participant must compete individually (or in teams if allowed)',
      '2 A theme or task will be given on the spot by the organizers',
      '3 Participants must create prompts to generate output using an AI tool',
      '4 Total time limit (eg, 15 – 30 minutes) must be strictly followed',
      '5 Only a limited number of prompts (eg, 2 – 3 attempts) are allowed',
      '6 Prompts must be original and created during the competition',
      '7 Copying prompts from others or using pre - written prompts is not allowed',
      '8 Final output must be generated only through AI (no manual editing)',
      '9 Any offensive or inappropriate content will lead to disqualification',
      '10 Judges’ decision will be final and based on creativity, relevance, and output quality'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Naresh Chaudhary', phone: '' }, { name: 'Nihar Vaghela', phone: '' }, { name: 'Vishva Yadav', phone: '' }, { name: 'Akshit Suvagiya', phone: '8799044109' }]
  },

  // ===== E-SPORTS =====
  { 
    id: 'free-fire', 
    name: 'Free Fire', 
    fee: 100, 
    limit: '1 Member', 
    desc: 'Squad up and dominate the Free Fire battlefield.', 
    iconName: 'Gamepad',
    fullDescription: 'Gather your squad and drop into the Free Fire battleground! Compete in multiple rounds of intense battle royale action. Strategy, teamwork, and skill will determine the champion squad!',
    rules: [
      'Rules:',
      '1 Registration is Team (4 player)',
      '2 Entry Fee:200/ - Per Team',
      '3 Winner and runner will up get the prize pool of money',
      '4 Qualification Round:',
      '• Game Details: Free Fire MAX (Version:21031), Map: Bermuda',
      '• Mode: BR (E sport mode)',
      '• Top three teams shall proceed to the next round Based on point table',
      '5 Round No:01/02',
      '• Game Details: Free Fire MAX (Version:21031)',
      '• Mode: CS (E sport mode) (1vs1)',
      '6 Final Round',
      '• Game Details: Free Fire MAX (Version:21031)',
      '• Mode: CS (E sport mode) (1vs1)',
      'Important Notes:',
      '• In case of any grievance, decision taken by coordinator will be the final',
      '• Characters silks allow and Gun attributes not allow',
      '• If any internet related issues are occurred then college is not responsible for that',
      '• Qualifications of the round1 may be varying It depends on the number of registrations',
      '• Come on the exact time which is given you in the schedule of your matches Otherwise your team will be disqualified after waiting for some time',
      '• Any hacking activity visible than team is directly disqualify and take action on that team'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Nehang Patel', phone: '8160542170' }, { name: 'Gopalsinh Solanki', phone: '9016079149' }, { name: 'Ved Patel', phone: '6358904500' }, { name: 'Shivam Shing', phone: '' }]
  },
  { 
    id: 'ludo-king', 
    name: 'Ludo King', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Roll the dice and conquer the Ludo board!', 
    iconName: 'Dice1',
    fullDescription: 'The classic board game goes digital! Compete in Ludo King and prove your strategic thinking. Roll the dice, move your tokens, and be the first to get all four home. Simple rules, intense competition!',
    rules: [
      'Rules:',
      '1 Registration is Individual',
      '2 Entry Fee:50/ - Per Player',
      '3 Participants must bring their own mobile',
      '4 Winner and runner up gets the prize pool of money',
      '5 Qualification Round:',
      '• The Total Number of Group (Size:4 members/Group) will be formed by Coordinator',
      '• Game Details: Ludo king (Version :840287)',
      '• The Individual winner (occupying 1 st Position) from each group will proceed for next Round No:01',
      '6 Round No:01/02/03',
      '• The Groups (4 members/Group) will be formed by Coordinator',
      '• Game Details: Ludo king (Version :840287)',
      '• The Individual winner (occupying 1 st Position) from each group will proceed for next Round No: 02/03',
      '7 Final Round',
      '• There will be only 4 players which play in single group',
      '• Game Details: Ludo king (Version :840287)',
      '• The winner (occupying 1 st Position) and runner up (occupying2nd position) from the group will be entitle as “Winner of Ludo king ”',
      'Important Notes:',
      '• In case of any grievance, decision taken by coordinator will be the final',
      '• Your team must report/be present on time at given venue otherwise your team shall be disqualified'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Nehang Patel', phone: '8160542170' }, { name: 'Gopalsinh Solanki', phone: '9016079149' }, { name: 'Ved Patel', phone: '6358904500' }, { name: 'Shivam Shing', phone: '' }]
  },
  { 
    id: 'bgmi', 
    name: 'BGMI Tournament', 
    fee: 400, 
    limit: '4 Member', 
    desc: 'Compete in the ultimate battle royale.', 
    iconName: 'Gamepad',
    fullDescription: 'Gather your squad and drop into the battlefield! The BGMI Tournament at PRAXES 2K26 is the ultimate test of teamwork, strategy, and gaming skill.',
    rules: [
      '• All players must use the official Battlegrounds Mobile India (BGMI) app',
      '• Each team must consist of 4 players (Squad)',
      '• Each team can have 1 substitute player (optional)',
      '• Players must register before the given deadline',
      '• Every player must have a valid BGMI ID and username',
      '• Only registered players are allowed to participate (no last - minute changes)',
      '• Tournament format (Solo/Duo/Squad) will be decided by organizers (usually Squad)',
      '• Matches will be played in Custom Rooms created by organizers',
      '• Room ID and password will be shared before the match',
      '• Players must join the room on time; late entry is not allowed',
      '• Use of emulators is strictly prohibited (mobile devices only)',
      '• Use of hacks, cheats, or unfair means will lead to immediate disqualification',
      '• Teaming with opponents is not allowed',
      '• Abusive language or misconduct will not be tolerated',
      '• Internet connection issues are the player’s responsibility',
      '• No rematch will be given due to personal technical problems',
      '• Points will be awarded based on kills and final position',
      '• Example: Chicken Dinner = highest points, each kill = extra points',
      '• In case of a tie, total kills will be considered',
      '• All players must follow instructions given by organizers',
      '• Spectators or outsiders are not allowed in the room',
      '• Players must keep their in - game name same as registered name',
      '• Any rule violation may lead to warning or disqualification',
      '• Organizers’ and referees’ decisions will be final'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Nehang Patel', phone: '8160542170' }, { name: 'Gopalsinh Solanki', phone: '9016079149' }, { name: 'Ved Patel', phone: '6358904500' }, { name: 'Shivam Shing', phone: '' }]
  },

  // ===== CULTURAL & CREATIVE =====
  { 
    id: 'rangoli', 
    name: 'Rangoli', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Create stunning rangoli art with vibrant colors.', 
    iconName: 'Palette',
    fullDescription: 'Unleash your artistic skills by creating beautiful rangoli designs! Use vibrant colors, flowers, and materials to craft mesmerizing patterns. Creativity, neatness, and use of colors will be judged.',
    rules: [
      '1 General Theme of the Rangoli Competition is on: Unity in diversity, social media and technologies, Subject (Branch) Oriented',
      '2 There will be only one round of competition',
      '3 Maximum 2 members are allowed in one team',
      '4 Maximum time to complete the Rangoli is two hours',
      '5 College will be responsible for arrangement of the material required to prepare Rangoli',
      '6 The participants will not be allowed to refer to any printed material etc for preparing Rangoli',
      '7 Any act of indiscipline by participants calls for cancellation of registration',
      '8 Slots will be given on first - come, first - served basis',
      '9 Evaluation will be based on Creativity, Clarity, Colors, Artistry and Theme conveyed',
      '10 The judges’ decision will be final',
      '11 During the competition no student is allowed to carry any kind of paper materials or any electronic gadgets like mobile etc',
      '12 Certificate will be given to each participant',
      '13 Be responsible for making the rangoli at the pre - decided location Volunteer shall help and support for the same',
      '14 Prize will be given to 1st and 2nd winner',
      '15 Venue: Civil Engineering Department 1st floor Guidelines for Rangoli:',
      '1 Rangoli art should be of 3ft x 3ft',
      '2 Only Rangoli Colors or colored sand should be used',
      '3 Space will be Provided within that space rangoli should be made'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Preeti Chaudhari', phone: '' }, { name: 'Shaili Patel', phone: '' }]
  },
  { 
    id: 'on-the-spot-painting', 
    name: 'On-The-Spot Painting', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Paint your imagination on canvas in real-time.', 
    iconName: 'Palette',
    fullDescription: 'Grab your brushes and let creativity flow! Topics will be given on the spot, and participants must create a painting within the time limit. Any painting medium is allowed.',
    rules: [
      '• All participants must bring ID card of college',
      '• You can participate in the event individually or in a team of maximum two participants',
      '• Only 1 person can participate in Drawing and Stone painting',
      '• Participants have to work on the theme',
      '• Maximum time is 2 hours for particular art and Craft',
      '• Participants are not allowed to refer any printed material or phone',
      '• Required materials are provided from the college',
      '• Judge ‘s decision will be final',
      '• Certificate will be given to each participant',
      '• Any action of indecipline by participant calls for cancellation of registration',
      '• The quality of the world should be judged based on the Quality, Neatness, Clarity of theme, Creativity and Originality'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Zainika Chaudhary', phone: '' }, { name: 'Zeel Patel', phone: '' }, { name: 'Isha Chaudhary', phone: '' }, { name: 'Jiya Joshi', phone: '' }, { name: 'Shruti Rathod', phone: '' }, { name: 'Charvi Patel', phone: '' }, { name: 'Mahek Patil', phone: '' }, { name: 'Nikita Chaudhary', phone: '' }, { name: 'Manisha Darji', phone: '' }, { name: 'Jiya Prajapati', phone: '' }, { name: 'Saloni Prajapati', phone: '' }, { name: 'Janvi Chaudhary', phone: '' }]
  },
  { 
    id: 'collage', 
    name: 'Collage Making', 
    fee: 30, 
    limit: '1 Member', 
    desc: 'Create beautiful collages from cut-outs and materials.', 
    iconName: 'Layers',
    fullDescription: 'Express your creativity through collage art! Use magazines, newspapers, colored paper, and other materials to create a stunning collage on the given theme.',
    rules: [
      '• All participants must bring ID card of college',
      '• You can participate in the event individually or in a team of maximum two participants',
      '• Only 1 person can participate in Drawing and Stone painting',
      '• Participants have to work on the theme',
      '• Maximum time is 2 hours for particular art and Craft',
      '• Participants are not allowed to refer any printed material or phone',
      '• Required materials are provided from the college',
      '• Judge ‘s decision will be final',
      '• Certificate will be given to each participant',
      '• Any action of indecipline by participant calls for cancellation of registration',
      '• The quality of the world should be judged based on the Quality, Neatness, Clarity of theme, Creativity and Originality'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Zainika Chaudhary', phone: '' }, { name: 'Zeel Patel', phone: '' }, { name: 'Isha Chaudhary', phone: '' }, { name: 'Jiya Joshi', phone: '' }, { name: 'Shruti Rathod', phone: '' }, { name: 'Charvi Patel', phone: '' }, { name: 'Mahek Patil', phone: '' }, { name: 'Nikita Chaudhary', phone: '' }, { name: 'Manisha Darji', phone: '' }, { name: 'Jiya Prajapati', phone: '' }, { name: 'Saloni Prajapati', phone: '' }, { name: 'Janvi Chaudhary', phone: '' }]
  },
  { 
    id: 'poster-making', 
    name: 'Poster Making', 
    fee: 30, 
    limit: '1 Member', 
    desc: 'Design impactful posters on given themes.', 
    iconName: 'PenTool',
    fullDescription: 'Create visually striking posters that convey powerful messages! The theme will be given on the spot. Judged on creativity, message clarity, and artistic skill.',
    rules: [
      '• All participants must bring ID card of college',
      '• You can participate in the event individually or in a team of maximum two participants',
      '• Only 1 person can participate in Drawing and Stone painting',
      '• Participants have to work on the theme',
      '• Maximum time is 2 hours for particular art and Craft',
      '• Participants are not allowed to refer any printed material or phone',
      '• Required materials are provided from the college',
      '• Judge ‘s decision will be final',
      '• Certificate will be given to each participant',
      '• Any action of indecipline by participant calls for cancellation of registration',
      '• The quality of the world should be judged based on the Quality, Neatness, Clarity of theme, Creativity and Originality'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Zainika Chaudhary', phone: '' }, { name: 'Zeel Patel', phone: '' }, { name: 'Isha Chaudhary', phone: '' }, { name: 'Jiya Joshi', phone: '' }, { name: 'Shruti Rathod', phone: '' }, { name: 'Charvi Patel', phone: '' }, { name: 'Mahek Patil', phone: '' }, { name: 'Nikita Chaudhary', phone: '' }, { name: 'Manisha Darji', phone: '' }, { name: 'Jiya Prajapati', phone: '' }, { name: 'Saloni Prajapati', phone: '' }, { name: 'Janvi Chaudhary', phone: '' }]
  },
  { 
    id: 'clay-modeling', 
    name: 'Clay Modeling', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Sculpt your imagination with clay.', 
    iconName: 'Star',
    fullDescription: 'Shape your ideas into reality using clay! Participants must create a model based on the given theme. Creativity, detail, and craftsmanship will be judged.',
    rules: [
      '• All participants must bring ID card of college',
      '• You can participate in the event individually or in a team of maximum two participants',
      '• Only 1 person can participate in Drawing and Stone painting',
      '• Participants have to work on the theme',
      '• Maximum time is 2 hours for particular art and Craft',
      '• Participants are not allowed to refer any printed material or phone',
      '• Required materials are provided from the college',
      '• Judge ‘s decision will be final',
      '• Certificate will be given to each participant',
      '• Any action of indecipline by participant calls for cancellation of registration',
      '• The quality of the world should be judged based on the Quality, Neatness, Clarity of theme, Creativity and Originality'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Zainika Chaudhary', phone: '' }, { name: 'Zeel Patel', phone: '' }, { name: 'Isha Chaudhary', phone: '' }, { name: 'Jiya Joshi', phone: '' }, { name: 'Shruti Rathod', phone: '' }, { name: 'Charvi Patel', phone: '' }, { name: 'Mahek Patil', phone: '' }, { name: 'Nikita Chaudhary', phone: '' }, { name: 'Manisha Darji', phone: '' }, { name: 'Jiya Prajapati', phone: '' }, { name: 'Saloni Prajapati', phone: '' }, { name: 'Janvi Chaudhary', phone: '' }]
  },
  { 
    id: 'cartooning', 
    name: 'Cartooning', 
    fee: 30, 
    limit: '1 Member', 
    desc: 'Draw hilarious and creative cartoons.', 
    iconName: 'Pencil',
    fullDescription: 'Show off your cartooning skills! Create funny, satirical, or creative cartoons or caricatures on the given theme. Humor, creativity, and drawing skill will be evaluated.',
    rules: [
      '• All participants must bring ID card of college',
      '• You can participate in the event individually or in a team of maximum two participants',
      '• Only 1 person can participate in Drawing and Stone painting',
      '• Participants have to work on the theme',
      '• Maximum time is 2 hours for particular art and Craft',
      '• Participants are not allowed to refer any printed material or phone',
      '• Required materials are provided from the college',
      '• Judge ‘s decision will be final',
      '• Certificate will be given to each participant',
      '• Any action of indecipline by participant calls for cancellation of registration',
      '• The quality of the world should be judged based on the Quality, Neatness, Clarity of theme, Creativity and Originality'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Zainika Chaudhary', phone: '' }, { name: 'Zeel Patel', phone: '' }, { name: 'Isha Chaudhary', phone: '' }, { name: 'Jiya Joshi', phone: '' }, { name: 'Shruti Rathod', phone: '' }, { name: 'Charvi Patel', phone: '' }, { name: 'Mahek Patil', phone: '' }, { name: 'Nikita Chaudhary', phone: '' }, { name: 'Manisha Darji', phone: '' }, { name: 'Jiya Prajapati', phone: '' }, { name: 'Saloni Prajapati', phone: '' }, { name: 'Janvi Chaudhary', phone: '' }]
  },
  { 
    id: 'mehandi', 
    name: 'Mehandi', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Design intricate and beautiful mehandi patterns.', 
    iconName: 'Palette',
    fullDescription: 'Showcase your mehandi artistry! Create intricate, beautiful henna designs. Participants will be judged on creativity, neatness, and complexity of patterns.',
    rules: [
      '1 The competition is open to all participants (individual entry only)',
      '2 Participants must bring their own Mehandi (henna) materials',
      '3 A fixed time limit will be given (eg, 30 – 60 minutes)',
      '4 Design must be applied on one hand only (usually palm or back, as specified)',
      '5 Only natural Mehandi cones are allowed; no artificial colors or stickers',
      '6 Participants must create designs on their own (no external help allowed)',
      '7 Use of mobile phones, books, or printed designs is not allowed',
      '8 Design should be neat, clear, and creative',
      '9 Participants must stop applying Mehandi when time is over',
      '10 Judging will be based on creativity, neatness, design complexity, and finishing',
      '11 Any late submission or incomplete design may lead to disqualification',
      '12 Decision of judges will be final and binding'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: []
  },
  { 
    id: 'photography', 
    name: 'Photography', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Capture moments through your creative lens.', 
    iconName: 'Camera',
    fullDescription: 'Capture the beauty around you! Participants will be given themes and must click photographs within the event premises. Composition, creativity, and storytelling through images will be judged.',
    rules: [
      '• Participant has to registered individually',
      '• Participant can use Professional Camera or smart phone',
      '• Participant has to capture the image with in GEC Palanpur campus',
      '• Participant has to best photograph to event faculty coordinator before 3pm',
      '• Participant can edit photographs',
      '• best two (winner and runner up) will get winning certificates',
      '• Rest Participant will get participation certificate',
      '• Do not capture photograph of any person without their permission'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Rani Chauhan', phone: '' }]
  },

  // ===== LITERARY & MEDIA =====
  { 
    id: 'short-film', 
    name: 'Short Film / Documentary', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Create compelling short films or documentaries.', 
    iconName: 'Film',
    fullDescription: 'Tell your story through the lens! Teams can create short films, documentaries, or social media content. Pre-recorded entries will be submitted and screened. Storytelling, cinematography, and editing will be judged.',
    rules: [
      '1 The film must be based on the given theme or topic (if provided)',
      '2 The duration of the film should be within the specified time limit (eg, 3 – 10 minutes)',
      '3 The content must be original and not copied from any source',
      '4 Participants can work individually or in a team (as per rules)',
      '5 Use of inappropriate, offensive, or copyrighted material is not allowed',
      '6 The film must include proper audio and video quality',
      '7 Language used should be clear and understandable (subtitles can be added if needed)',
      '8 Participants must submit the film before the deadline',
      '9 Basic editing is allowed, but excessive special effects should not overpower the content',
      '10 Credits must be given for music, clips, or any external resources used',
      '11 The film should clearly convey a message or story related to the theme',
      '12 Judging will be based on creativity, content, direction, and presentation'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Tirth Patel', phone: '' }, { name: 'Chetan Thakor', phone: '' }, { name: 'Ashokji Solanki', phone: '' }]
  },
  { 
    id: 'debate', 
    name: 'Debate', 
    fee: 30, 
    limit: '1 Member', 
    desc: 'Argue your case with logic and eloquence.', 
    iconName: 'MessageSquare',
    fullDescription: 'Battle it out with words! Participants will debate on thought-provoking topics. Persuasion, logic, knowledge, and presentation skills will determine the winner.',
    rules: [
      'DEBATE RULES 1) There are two teams, each consisting of two or three speakers 2) If speakers make statement they must be able to provide evidence or reason to support the statement 3) Facts presented in debates must be accurate 4) Each team must use the proper language 5) Winner is decided on the basis of how the team has expressed their point with proper reasons as well as how they deliver their points'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Raghu Prajapati', phone: '' }, { name: 'Mihir Raval', phone: '9586507812' }, { name: 'Prerak Barot', phone: '' }]
  },
  { 
    id: 'story-on-pic', 
    name: 'Story on Pic', 
    fee: 30, 
    limit: '1 Member', 
    desc: 'Weave creative stories inspired by an image.', 
    iconName: 'BookOpen',
    fullDescription: 'A picture speaks a thousand words — now write them! Participants will be shown an image and must craft a creative story inspired by it. Imagination, writing skill, and narrative flow will be judged.',
    rules: [
      '• All participants must bring their id card of college',
      '• There will be 15 min to write a story of one photo and there are 3 rounds and in one round 1 photo will be shown to the participants',
      '• Writing language must be in English and Gujarati',
      '• Minimum numbers of words you have to write is 100 - 150 words',
      '• Participants gets the e - certificate of the participation',
      '• To write a story, pages will be provided by the college',
      '• Winner and runner up gets the book as a prize of this event',
      '• Any digital device is not allowed',
      '• Judge’s decisions are the final decisions Evaluation of the story will be based on their abstract, writing skill, grammar'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Shivam Panchal', phone: '' }, { name: 'Divyansh Jadhav', phone: '' }]
  },
  { 
    id: 'writing', 
    name: 'Writing', 
    fee: 30, 
    limit: '1 Member', 
    desc: 'Express yourself through the power of words.', 
    iconName: 'Pencil',
    fullDescription: 'Pen down your thoughts! Whether it\'s essay writing, poetry, or creative writing — showcase your literary talent. Topics will be given on the spot.',
    rules: [
      '1 A topic or theme must be given to all participants',
      '2 Each participant must write individually without any help',
      '3 A fixed time limit must be followed (eg, 15 – 30 minutes)',
      '4 A word limit must be maintained as instructed',
      '5 The content must be original (no copying allowed)',
      '6 Writing must be relevant to the given topic',
      '7 Proper grammar, spelling, and punctuation must be used',
      '8 The writing should be clear and neatly presented',
      '9 Use of creative ideas and imagination is encouraged',
      '10 No use of mobile phones or external materials is allowed',
      '11 Participants must stop writing immediately when time is over',
      '12 All entries will be evaluated based on creativity, clarity, and correctness'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Ami Prajapati', phone: '' }, { name: 'Saloni Prajapati', phone: '' }]
  },

  // ===== FUN & GAMES =====
  { 
    id: 'cooking', 
    name: 'Cooking', 
    fee: 150, 
    limit: '4 Member', 
    desc: 'Cook up delicious dishes in this culinary showdown.', 
    iconName: 'ChefHat',
    fullDescription: 'Put on your chef hat and cook up something amazing! Teams will prepare dishes under time constraints. Taste, presentation, creativity, and hygiene will be judged.',
    rules: [
      '1 One team may contain a maximum of 2 members',
      '2 Total preparation Time: 1 Hours',
      '3 Participants are required to report 30 minutes prior to the commencement of the event at the venue',
      '4 Cutting of vegetables or fruits should be done on the spot No prior preparation is allowed',
      '5 Milk and milk products can be used (Cheese, butter, ghee, curd, etc)',
      '6 Items like poha (aval), puffed rice, bread, mayonnaise , boiled item (Eg: - Potato ,chana ,mag etc), home made chatni are allowed',
      '7 Readymade decorative items are not permitted',
      '8 Participants should get approval for their raw materials one day prior to the competition',
      '9 Participants should arrange separate glass, spoons, plates and similar cutlery items for three judges',
      '10 Heating by any method is not permitted',
      '11 Participants should maintain cleanliness by all means and raw materials/ prepared items should be hygiene',
      '12 Participants should clean their respective workplaces after the competition',
      '13 Judges decision will be final',
      '14 Mixers can be used',
      '15 Participants are required to bring their own cutlery, utensils, and ingredients',
      '16 Mark distribution: Presentation:10 Marks, Taste: 10 Marks, Nutrition: 10 Marks , Cleanliness:10'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Vishakha Modi', phone: '' }, { name: 'Vishwa Varde', phone: '' }]
  },
  { 
    id: 'treasure-hunt', 
    name: 'Treasure Hunt', 
    fee: 200, 
    limit: '4 Member', 
    desc: 'Follow clues and find the hidden treasure!', 
    iconName: 'Compass',
    fullDescription: 'An exciting campus-wide treasure hunt! Teams will follow a series of cryptic clues hidden across the campus. The first team to find all clues and reach the treasure wins!',
    rules: [
      '• Exploration Place shall be campus of GEC Palanpur',
      '• This event is only for students of GEC, Palanpur',
      '• Combination of any branch/any gender is allowed',
      '• Compulsory 5 members should be in a team',
      '• Miss behaving with coordinators or volunteers may lead to team disqualification',
      '• Organizers have the authority to disqualify any team if rules are found to be violated',
      '• Keep your college id for verification during the event',
      '• In any circumstances, the final decision is taken by coordinators',
      '• The volunteer may be present at each stage of the event and will monitor your progress',
      '• Not to damage anything in college while playing game',
      '• Teams must stay together during the Treasure Hunt'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Jay Patel', phone: '' }, { name: 'Savan Patel', phone: '' }, { name: 'Aditya Devdatt', phone: '' }, { name: 'Bhavya Patel', phone: '' }, { name: 'Jil Patel', phone: '' }]
  },
  { 
    id: 'laser-maze', 
    name: 'Laser Maze', 
    fee: 50, 
    limit: '2 Member', 
    desc: 'Navigate through a thrilling laser obstacle course.', 
    iconName: 'Zap',
    fullDescription: 'Channel your inner secret agent! Navigate through a maze of laser beams without triggering any. Speed and agility are key. The participant who clears the maze fastest with fewest touches wins!',
    rules: [
      'Ø 3 participate available',
      'Ø Don’t share given pattern',
      'Ø Time limit for particular pattern',
      'Ø If your team shakes the glass on the table and scatters it, the team will be held responsible',
      'Ø Don’t argument with given pattern',
      'Ø Make perfect pattern',
      'Ø Coordinator decision is the final decision'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Vasudev Shaini', phone: '' }, { name: 'Kuldeep Chauhan', phone: '' }]
  },
  { 
    id: 'darts', 
    name: 'Darts', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Test your aim and precision with darts.', 
    iconName: 'Target',
    fullDescription: 'Aim, throw, score! Test your precision and focus in this classic darts competition. Multiple rounds of increasing difficulty will determine the sharpest shooter!',
    rules: [
      '• Players start with 501 or 301 points',
      '• Player and dart board distance 8 feet',
      '• Players take turns throwing three darts at the board one at a time',
      '• Players calculate their score for each turn and subtract it from their total at the end of their turn',
      '• The score for each turn is the sum of the scores of each dart thrown',
      '• A dart in the bullseye scores 50 points, the outer ring scores 25 points, and a dart in the double or treble ring counts double or treble the segment score',
      '• The objective is to "own" or "close" certain numbers on the board and achieve the highest point score',
      '• Players should only throw darts needed to win',
      '• Players should stand on the throwing line',
      '• Players should not touch darts until after their turn',
      '• Players should record their score before removing darts',
      '• Dropped darts can be thrown again',
      '• Any dart thrown counts as a throw, whether or not it is registered on the machine',
      '• Maximum time is 2 hours for particular darts game '
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Nidhi Shiyal', phone: '' }, { name: 'Abhijit Chauhan', phone: '' }, { name: 'Vandit Prajapati', phone: '' }, { name: 'Pranjal Chaudhary', phone: '' }]
  },
  { 
    id: 'talent-show', 
    name: 'Talent Show', 
    fee: 100, 
    limit: '1 Member', 
    desc: 'Showcase any talent — singing, dancing, magic, and more!', 
    iconName: 'Mic',
    fullDescription: 'Got a unique talent? This is your stage! Whether it\'s singing, dancing, comedy, magic, beatboxing, or anything else — the Talent Show is an open platform for all performers.',
    rules: [
      '• Event of Talent show',
      '1 Singing',
      '2 Dancing',
      '3 Lip - syncing',
      '4 Acting',
      '5 Martial arts',
      '6 Playing an instrument',
      '7 Poetry',
      '8 Comedy Or other activities to Showcase skills',
      '• Rules of Talent show',
      '• All participants must bring ID card of college',
      '• You can participate in the event individually',
      '• Maximum time is 5 minutes for particular talent',
      '• Required materials are provided from the college',
      '• Judge ‘s decision will be final',
      '• Certificate will be given to each participant',
      '• Prize will be given to Frist 3 winners',
      '• Any action of indiscipline by participant calls for cancellation of registration',
      '• The quality of the world should be judged based on the your talent and performance',
      '• Venue: - Central Garden'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Bansi Chavda', phone: '' }, { name: 'Vaishnav Tandel', phone: '7862910643' }, { name: 'Umangi Patel', phone: '' }, { name: 'Nikul Prajapati', phone: '9316129543' }]
  },
  { 
    id: 'mind-marathon', 
    name: 'Mind Marathon', 
    fee: 30, 
    limit: '1 Member', 
    desc: 'Push your mental limits with brain-teasing puzzles.', 
    iconName: 'Brain',
    fullDescription: 'A marathon for your mind! Solve a series of brain teasers, logic puzzles, riddles, and aptitude questions. Speed and accuracy will determine the champion.',
    rules: [
      'Ø The game can be played individually or in teams',
      'Ø A quizmaster or host asks a series of questions',
      'Ø Questions can include:',
      '• General knowledge',
      '• Puzzles',
      '• Logical reasoning',
      '• Math or riddles',
      'Ø Each question has a time limit (eg, 10 – 30 seconds)',
      'Ø Players/teams must answer within the time limit',
      'Ø A correct answer earns points (eg, +10 points)',
      'Ø A wrong answer may give no points or negative points (depending on rules)',
      'Ø If a team cannot answer, the question may pass to another team',
      'Ø Some rounds may be rapid - fire rounds where many questions are asked quickly',
      'Ø Use of phones, books, or outside help is not allowed',
      'Ø The game continues for a fixed number of rounds or time',
      'Ø The player/team with the highest total score wins'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Yahraj Vaishnav', phone: '' }, { name: 'Mayur Vagda', phone: '' }, { name: 'Raj Patel', phone: '9316353835' }, { name: 'Krishana Tank', phone: '' }, { name: 'Sonal Chudhary', phone: '' }]
  },
  { 
    id: 'tower-of-hanoi', 
    name: 'Tower of Hanoi', 
    fee: 30, 
    limit: '1 Member', 
    desc: 'Solve the classic Tower of Hanoi puzzle the fastest.', 
    iconName: 'Puzzle',
    fullDescription: 'The classic mathematical puzzle comes to life! Move all disks from one peg to another following the rules. Fewest moves and fastest time wins. A true test of logic and planning!',
    rules: [
      '1 There are three rods (A, B, and C)',
      '2 There are n disks of different sizes placed on one rod',
      '3 All disks start on a single rod in descending order (largest at bottom, smallest at top)',
      '4 The goal is to move all disks to another rod',
      '5 Only one disk can be moved at a time',
      '6 A disk can only be moved if it is the top disk on its rod',
      '7 A disk can be placed either:',
      '8 On an empty rod, or',
      '9 On top of a larger disk',
      '10 A larger disk cannot be placed on a smaller disk',
      '11 You must follow all rules until all disks are transferred correctly to the target rod'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Mahimn Joshi', phone: '7041997504' }, { name: 'Jenil Kotadiya', phone: '' }]
  },
  { 
    id: 'rubiks-cube', 
    name: "Rubik's Cube", 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Solve the Rubik\'s Cube in record time.', 
    iconName: 'Puzzle',
    fullDescription: 'How fast can you solve it? Compete against the best cubers to solve the 3x3 Rubik\'s Cube in the shortest time. Multiple attempts, best time counts!',
    rules: [
      '1 Registration is mandatory for all participants',
      '2 Participants must use a standard 3×3 Rubik’s Cube (unless another category is specified)',
      '3 The cube will be scrambled by the organizer or judge before the start',
      '4 The participant must start solving only after the signal is given',
      '5 Time starts and stops based on the official timer or judge’s command',
      '6 The cube must be solved with all faces having one single color',
      '7 Misalignment or incomplete solve will not be accepted',
      '8 Participants must not use mobile phones, notes, or external help',
      '9 Damaging or changing the cube mechanism during the game is not allowed',
      '10 Winner is decided based on the fastest solving time, and the judges’ decision will be final'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Het Patel', phone: '9409308699' }, { name: 'Dax Mane', phone: '6354757812' }, { name: 'Adarsh Shukla', phone: '8866948270' }]
  },
  { 
    id: 'fun-games', 
    name: 'Fun Games', 
    fee: 50, 
    limit: '1 Member', 
    desc: 'Enjoy a variety of fun and exciting mini-games.', 
    iconName: 'Flame',
    fullDescription: 'Non-stop fun with a variety of exciting mini-games! From relay races to quirky challenges, there\'s something for everyone. Come, participate, and have a blast!',
    rules: [
      'Solo or team participation depending on the game'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM Onward',
    prize: 'TBA',
    coordinators: [{ name: 'Himanshu Nai', phone: '9875017538' }, { name: 'Rivanshi Darji', phone: '' }, { name: 'Yash Thakkar', phone: '7990956937' }, { name: 'Bhoomi Sadhu', phone: '' }, { name: 'Hardik Chaudhary', phone: '9499775348' }, { name: 'Kuldip Parmar', phone: '' }, { name: 'Devansh Prajapati', phone: '' }, { name: 'Smit Vaghela', phone: '' }, { name: 'Man Patel', phone: '9408309232' }, { name: 'Tejashvi davda', phone: '' }, { name: 'Shubham Patel', phone: '8320425345' }, { name: 'Pratham Parmar', phone: '9427512951' }]
  },
  { 
    id: 'mind-marathon-duo', 
    name: 'Mind Marathon (Duo)', 
    fee: 60, 
    limit: '2 Member', 
    desc: 'Push your mental limits with brain-teasing puzzles.', 
    iconName: 'Brain',
    fullDescription: 'A marathon for your mind! Solve a series of brain teasers, logic puzzles, riddles, and aptitude questions. Speed and accuracy will determine the champion.',
    rules: [
      'Ø The game can be played individually or in teams',
      'Ø A quizmaster or host asks a series of questions',
      'Ø Questions can include:',
      '• General knowledge',
      '• Puzzles',
      '• Logical reasoning',
      '• Math or riddles',
      'Ø Each question has a time limit (eg, 10 – 30 seconds)',
      'Ø Players/teams must answer within the time limit',
      'Ø A correct answer earns points (eg, +10 points)',
      'Ø A wrong answer may give no points or negative points (depending on rules)',
      'Ø If a team cannot answer, the question may pass to another team',
      'Ø Some rounds may be rapid - fire rounds where many questions are asked quickly',
      'Ø Use of phones, books, or outside help is not allowed',
      'Ø The game continues for a fixed number of rounds or time',
      'Ø The player/team with the highest total score wins'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM ONWARD',
    prize: 'TBA',
    coordinators: [{ name: 'Yahraj Vaishnav', phone: '' }, { name: 'Mayur Vagda', phone: '' }, { name: 'Raj Patel', phone: '9316353835' }, { name: 'Krishana Tank', phone: '' }, { name: 'Sonal Chudhary', phone: '' }]
  },
  { 
    id: 'robo-race-squad', 
    name: 'Robo Race (squad)', 
    fee: 400, 
    limit: '4 Member', 
    desc: 'Build and race your robot through challenging tracks.', 
    iconName: 'Bot',
    fullDescription: 'Design a fast, agile robot and race it through an obstacle-filled track! Teams must build autonomous or remote-controlled robots that can navigate turns, ramps, and hurdles. The fastest robot to complete the track wins!',
    rules: [
      '1 Registration is compulsory for all participants or teams before the race',
      '2 Each team can have only one robot in the competition',
      '3 Robots must follow the given size and weight limits set by organizers',
      '4 The robot must be controlled manually or wirelessly (no fully autonomous bots unless allowed)',
      '5 The race will be conducted on a fixed track with obstacles',
      '6 Robots must stay on the track – leaving the track may lead to penalties or disqualification',
      '7 Damaging other robots is strictly prohibited',
      '8 Teams must complete the track within the given time limit',
      '9 Judging is based on speed, control, and successful completion of obstacles',
      '10 Judges’ decision will be final and binding',
      'Robot Specification:',
      '1 The maximum dimension of the robot can be 30 cm x 30 cm x 30 cm (l x b x h)',
      '2 The robot may be wired or wireless',
      '3 AC supply will be provided in the college',
      '4 The length of the wire (for wired bots) should be long enough to cover the whole track and wire should remain slack during the complete run',
      '5 Maximum weight must not exceed 3 kg',
      '6 The machine must be powered electrically only Use of IC engine is not allowed',
      '7 Batteries must be sealed, immobilized electrolyte type (gel cell, lithium, NiCad, or dry cells)',
      '8 The electric voltage anywhere in the machine should not be more than 12 V DC at any point of time'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM ONWARD',
    prize: 'TBA',
    coordinators: [{ name: 'Pradeep Chaudhary', phone: '8401889146' }, { name: 'Dax Padasala', phone: '' }, { name: 'Hiren Ajakiya', phone: '7863840941' }]
  },
  { 
    id: 'robo-war-squad', 
    name: 'Robo War (squad)', 
    fee: 400, 
    limit: '4 Member', 
    desc: 'Build and battle your robots in the ultimate arena.', 
    iconName: 'Shield',
    fullDescription: 'Design, build, and battle your robot in the most thrilling event of PRAXES 2K26! Robots will face off in a specially designed arena. The last robot standing wins!',
    rules: [
      '1 Each team can have a maximum of 4 – 5 members',
      '2 The robot must follow the size and weight limits given by organizers',
      '3 Matches are conducted between two robots in an arena',
      '4 The goal is to immobilize, flip, or push the opponent out of the arena',
      '5 Each match will have a fixed time duration (eg, 3 – 5 minutes)',
      '6 No Dangerous Weapons – Use of explosives, fire, liquids, or harmful weapons is strictly prohibited',
      '7 Intentional damage to the arena or unfair tactics will lead to disqualification',
      '8 Robots must be controlled manually or wirelessly; no external interference allowed',
      '9 Teams must follow all safety instructions during the match',
      '10 Winners are decided based on damage, control, aggression, and strategy, and the judges’ decision is final',
      'Robot Specification:',
      '1 Permissible weight: Maximum 06 kg (excluding off‐bot power equipment eg batteries, adapters etc)',
      '2 Maximum permissible volume Fully unfolded robot must be within the limits of 40 cm X 55 cm (l x b) There is no maximum height for a robot (dictated by the design and weight constraints)',
      '3 Robots can have weapons such as cutters, flippers, saws, lifting devices, spinning hammers etc Use of liquid projectiles, any kind of inflammable liquid, flame‐based weapons, radio jamming devices, high power magnets or electromagnets, are not permitted',
      '4 Use of IC Engines is not allowed',
      '5 We will provide on‐site power points of 230 V AC Participating teams need to bring their own adapters/converters (with a maximum output voltage of 24 V DC) to avail AC supply',
      '6 In case of batteries, maximum allowed voltage is 24 V DC',
      '7 If robot is wired, then maximum 45 m length is permitted'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM ONWARD',
    prize: 'TBA',
    coordinators: [{ name: 'Pradeep Chaudhary', phone: '8401889146' }, { name: 'Dax Padasala', phone: '' }, { name: 'Hiren Ajakiya', phone: '7863840941' }]
  },
  { 
    id: 'robo-soccer-squad', 
    name: 'Robo Soccer (squad)', 
    fee: 400, 
    limit: '4 Member', 
    desc: 'Control your robot to score goals in a thrilling soccer match.', 
    iconName: 'Bot',
    fullDescription: 'Build a robot that can play soccer! Teams compete in a custom arena, controlling their robots to score goals. Strategy, control, and teamwork are key to winning this exciting event.',
    rules: [
      'Robot Specification:',
      '• The robot must fit within a square the box of the following dimensions initially: Height: 30 cm Width: 30cm Length: 30cm',
      '• The total mass of the robot must not exceed 6 kg',
      '• Robots must be manually controlled Wired or wireless remotes can be used',
      '• Teams using wireless robots should use multi - frequency remotes to avoid frequency interference',
      '• Only one member would be allowed to control the bot during the match',
      '• The robot should be electrically powered The power supply must be on - board',
      '• The potential difference between any two points of the robot should not exceed 24V DC',
      '• Change of battery will not be allowed during the match',
      '• In the case of wired bots, the wires should remain slack during the fight',
      '• The wires should remain insulated and all the wires coming out of the machine should be stacked as a single unit',
      '• Parts that could break or damage the ring or opponent',
      '• Use of pneumatics, hydraulics, inflammable liquids, flame weapons, glue, RF jammers, and electromagnetic systems are strictly prohibited',
      '• The robots should not hold or grab the ball while moving Dribbler mechanisms can be used',
      '• The ball can be dribbled and hit from any part of the robot',
      '• Each bot must have a mechanism to hit the ball Hydraulics should not be used for any mechanisms'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM ONWARD',
    prize: 'TBA',
    coordinators: [{ name: 'Pradeep Chaudhary', phone: '8401889146' }, { name: 'Dax Padasala', phone: '' }, { name: 'Hiren Ajakiya', phone: '7863840941' }]
  },
  { 
    id: 'free-fire-squad', 
    name: 'Free Fire (squad)', 
    fee: 400, 
    limit: '4 Member', 
    desc: 'Squad up and dominate the Free Fire battlefield.', 
    iconName: 'Gamepad',
    fullDescription: 'Gather your squad and drop into the Free Fire battleground! Compete in multiple rounds of intense battle royale action. Strategy, teamwork, and skill will determine the champion squad!',
    rules: [
      'Rules:',
      '1 Registration is Team (4 player)',
      '2 Entry Fee:200/ - Per Team',
      '3 Winner and runner will up get the prize pool of money',
      '4 Qualification Round:',
      '• Game Details: Free Fire MAX (Version:21031), Map: Bermuda',
      '• Mode: BR (E sport mode)',
      '• Top three teams shall proceed to the next round Based on point table',
      '5 Round No:01/02',
      '• Game Details: Free Fire MAX (Version:21031)',
      '• Mode: CS (E sport mode) (1vs1)',
      '6 Final Round',
      '• Game Details: Free Fire MAX (Version:21031)',
      '• Mode: CS (E sport mode) (1vs1)',
      'Important Notes:',
      '• In case of any grievance, decision taken by coordinator will be the final',
      '• Characters silks allow and Gun attributes not allow',
      '• If any internet related issues are occurred then college is not responsible for that',
      '• Qualifications of the round1 may be varying It depends on the number of registrations',
      '• Come on the exact time which is given you in the schedule of your matches Otherwise your team will be disqualified after waiting for some time',
      '• Any hacking activity visible than team is directly disqualify and take action on that team'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM ONWARD',
    prize: 'TBA',
    coordinators: [{ name: 'Nehang Patel', phone: '8160542170' }, { name: 'Gopalsinh Solanki', phone: '9016079149' }, { name: 'Ved Patel', phone: '6358904500' }, { name: 'Shivam Shing', phone: '' }]
  },
  { 
    id: 'debate-squad', 
    name: 'Debate (squad)', 
    fee: 100, 
    limit: '4 Member', 
    desc: 'Argue your case with logic and eloquence.', 
    iconName: 'MessageSquare',
    fullDescription: 'Battle it out with words! Participants will debate on thought-provoking topics. Persuasion, logic, knowledge, and presentation skills will determine the winner.',
    rules: [
      'DEBATE RULES 1) There are two teams, each consisting of two or three speakers 2) If speakers make statement they must be able to provide evidence or reason to support the statement 3) Facts presented in debates must be accurate 4) Each team must use the proper language 5) Winner is decided on the basis of how the team has expressed their point with proper reasons as well as how they deliver their points'
    ],
    venue: 'GEC PALANPUR',
    date: 'April 8-9, 2026',
    time: '10 AM ONWARD',
    prize: 'TBA',
    coordinators: [{ name: 'Raghu Prajapati', phone: '' }, { name: 'Mihir Raval', phone: '9586507812' }, { name: 'Prerak Barot', phone: '' }]
  }
].sort((a, b) => a.name.localeCompare(b.name));

const EVENTS_VERSION = 5287; // Bump this when DEFAULT_EVENTS structure changes

export const getEventsList = () => {
  const savedVersion = localStorage.getItem('praxes_events_version');
  const saved = localStorage.getItem('praxes_events');
  
  if (saved && savedVersion === String(EVENTS_VERSION)) {
    try {
      const parsed = JSON.parse(saved);
      // Migration: convert to array if old version
      return parsed.map(ev => {
        if (!ev.coordinators) {
          ev.coordinators = [];
          if (ev.coordinatorName) ev.coordinators.push({ name: ev.coordinatorName, phone: ev.coordinatorPhone || '' });
          if (ev.coordinator2Name) ev.coordinators.push({ name: ev.coordinator2Name, phone: ev.coordinator2Phone || '' });
          delete ev.coordinatorName; delete ev.coordinatorPhone; delete ev.coordinator2Name; delete ev.coordinator2Phone;
        }
        return ev;
      });
    } catch (e) {
      console.error("Error parsing events from localStorage");
    }
  }
  // Initialize or refresh stale data
  localStorage.setItem('praxes_events', JSON.stringify(DEFAULT_EVENTS));
  localStorage.setItem('praxes_events_version', String(EVENTS_VERSION));
  return DEFAULT_EVENTS;
};

export const getEventById = (id) => {
  const events = getEventsList();
  return events.find(event => event.id === id) || null;
};

export const saveEventsList = (events) => {
  localStorage.setItem('praxes_events', JSON.stringify(events));
};

export const getIconComponent = (iconName, props = {}) => {
  const icons = {
    Cpu: <Cpu {...props} />,
    Shield: <Shield {...props} />,
    Music: <Music {...props} />,
    Code: <Code {...props} />,
    Gamepad: <Gamepad {...props} />,
    Mic: <Mic {...props} />,
    Monitor: <Monitor {...props} />,
    Zap: <Zap {...props} />,
    Star: <Star {...props} />,
    Bot: <Bot {...props} />,
    Trophy: <Trophy {...props} />,
    Compass: <Compass {...props} />,
    Palette: <Palette {...props} />,
    Camera: <Camera {...props} />,
    Target: <Target {...props} />,
    Brain: <Brain {...props} />,
    Cog: <Cog {...props} />,
    PenTool: <PenTool {...props} />,
    Film: <Film {...props} />,
    MessageSquare: <MessageSquare {...props} />,
    BookOpen: <BookOpen {...props} />,
    ChefHat: <ChefHat {...props} />,
    Layers: <Layers {...props} />,
    Puzzle: <Puzzle {...props} />,
    Dice1: <Dice1 {...props} />,
    Sparkles: <Sparkles {...props} />,
    Lightbulb: <Lightbulb {...props} />,
    Flame: <Flame {...props} />,
    Search: <Search {...props} />,
    Building: <Building {...props} />,
    Pencil: <Pencil {...props} />
  };
  return icons[iconName] || <Star {...props} />;
};
